//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 03:03:40 PM COT 
//

package seeit3d.model.xml.internal;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dl.dropbox.com/u/2416325/seeit3d_xsd}metricsList"/>
 *         &lt;element ref="{http://dl.dropbox.com/u/2416325/seeit3d_xsd}mapping" minOccurs="0"/>
 *         &lt;element ref="{http://dl.dropbox.com/u/2416325/seeit3d_xsd}polycylinder" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="granuralityLevelName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="has" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metricsList", "mapping", "polycylinder" })
@XmlRootElement(name = "container")
public class Container implements Serializable{

	private static final long serialVersionUID = 9116191952573837009L;

	@XmlElement(required = true)
	protected MetricsList metricsList;
	protected Mapping mapping;
	@XmlElement(required = true)
	protected List<Polycylinder> polycylinder;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String name;
	@XmlAttribute(required = true)
	protected String granularityLevelName;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object has;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object parent;

	/**
	 * Gets the value of the metricsList property.
	 * 
	 * @return possible object is {@link MetricsList }
	 * 
	 */
	public MetricsList getMetricsList() {
		return metricsList;
	}

	/**
	 * Sets the value of the metricsList property.
	 * 
	 * @param value
	 *            allowed object is {@link MetricsList }
	 * 
	 */
	public void setMetricsList(MetricsList value) {
		this.metricsList = value;
	}

	/**
	 * Gets the value of the mapping property.
	 * 
	 * @return possible object is {@link Mapping }
	 * 
	 */
	public Mapping getMapping() {
		return mapping;
	}

	/**
	 * Sets the value of the mapping property.
	 * 
	 * @param value
	 *            allowed object is {@link Mapping }
	 * 
	 */
	public void setMapping(Mapping value) {
		this.mapping = value;
	}

	/**
	 * Gets the value of the polycylinder property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
	 * not a <CODE>set</CODE> method for the polycylinder property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPolycylinder().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Polycylinder }
	 * 
	 * 
	 */
	public List<Polycylinder> getPolycylinder() {
		if (polycylinder == null) {
			polycylinder = new ArrayList<Polycylinder>();
		}
		return this.polycylinder;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the granuralityLevelName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */

	public String getGranularityLevelName() {
		return granularityLevelName;
	}

	/**
	 * Sets the value of the granuralityLevelName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */

	public void setGranularityLevelName(String granularityLevelName) {
		this.granularityLevelName = granularityLevelName;
	}

	/**
	 * Gets the value of the has property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getHas() {
		return has;
	}

	/**
	 * Sets the value of the has property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setHas(Object value) {
		this.has = value;
	}

	/**
	 * Gets the value of the parent property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getParent() {
		return parent;
	}

	/**
	 * Sets the value of the parent property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setParent(Object value) {
		this.parent = value;
	}

}
