//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 03:03:40 PM COT 
//

package seeit3d.modelers.xml.internal;

import java.io.Serializable;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://dl.dropbox.com/u/2416325/seeit3d_xsd}metricName"/>
 *         &lt;element name="visualProperty">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="COLOR"/>
 *               &lt;enumeration value="HEIGHT"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metricName", "visualProperty" })
@XmlRootElement(name = "mappingValue")
public class MappingValue implements Serializable{

	private static final long serialVersionUID = -2346931450259873892L;

	@XmlElement(required = true)
	protected String metricName;
	@XmlElement(namespace = "", required = true)
	protected String visualProperty;

	/**
	 * Gets the value of the metricName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMetricName() {
		return metricName;
	}

	/**
	 * Sets the value of the metricName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMetricName(String value) {
		this.metricName = value;
	}

	/**
	 * Gets the value of the visualProperty property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVisualProperty() {
		return visualProperty;
	}

	/**
	 * Sets the value of the visualProperty property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVisualProperty(String value) {
		this.visualProperty = value;
	}

}
